import Config

# Configure your database
config :ledger_loop, LedgerLoop.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("PGHOST") || "localhost",
  database: "ledger_loop_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ledger_loop, LedgerLoopWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1E2JSI1+eKgEauIWXniOv9+E05Ses3L8mLv7Ux7YwO22vUILloECAPW73JGQkng5",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ledger_loop, LedgerLoopWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ledger_loop_web/router\.ex$"E,
      ~r"lib/ledger_loop_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Use polling backend so file-change events propagate across the macOS→Docker bind mount.
# This is the application-env key that controls HOW files are watched — it MUST be a
# separate top-level block here, NOT merged into the Endpoint block above (backend: placed
# inside the Endpoint keyword is silently ignored; DKR-04, Pitfall 1 from research).
config :phoenix_live_reload,
  backend: :fs_poll,
  backend_opts: [interval: 500]

# Enable dev routes for dashboard and mailbox
config :ledger_loop, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
