services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev --import-realm --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./realm-relyra-adoption.json:/opt/keycloak/data/import/realm-relyra-adoption.json
